# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='payment',
            field=models.CharField(choices=[('Gamer', 'Gamer'), ('Developer', 'Developer')], default='Gamer', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15),
        ),
    ]
